# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/salvatore/FRT/nodi/ros_canopen/socketcan_interface

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/salvatore/FRT/nodi/ros_canopen/socketcan_interface

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\" \"cmake\" \"pkgconfig\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/salvatore/FRT/nodi/ros_canopen/socketcan_interface/CMakeFiles /home/salvatore/FRT/nodi/ros_canopen/socketcan_interface//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/salvatore/FRT/nodi/ros_canopen/socketcan_interface/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named socketcan_interface_string

# Build rule for target.
socketcan_interface_string: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 socketcan_interface_string
.PHONY : socketcan_interface_string

# fast build rule for target.
socketcan_interface_string/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/socketcan_interface_string.dir/build.make CMakeFiles/socketcan_interface_string.dir/build
.PHONY : socketcan_interface_string/fast

#=============================================================================
# Target rules for targets named socketcan_dump

# Build rule for target.
socketcan_dump: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 socketcan_dump
.PHONY : socketcan_dump

# fast build rule for target.
socketcan_dump/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/socketcan_dump.dir/build.make CMakeFiles/socketcan_dump.dir/build
.PHONY : socketcan_dump/fast

#=============================================================================
# Target rules for targets named socketcan_bcm

# Build rule for target.
socketcan_bcm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 socketcan_bcm
.PHONY : socketcan_bcm

# fast build rule for target.
socketcan_bcm/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/socketcan_bcm.dir/build.make CMakeFiles/socketcan_bcm.dir/build
.PHONY : socketcan_bcm/fast

#=============================================================================
# Target rules for targets named socketcan_interface_plugin

# Build rule for target.
socketcan_interface_plugin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 socketcan_interface_plugin
.PHONY : socketcan_interface_plugin

# fast build rule for target.
socketcan_interface_plugin/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/socketcan_interface_plugin.dir/build.make CMakeFiles/socketcan_interface_plugin.dir/build
.PHONY : socketcan_interface_plugin/fast

#=============================================================================
# Target rules for targets named console_bridge

# Build rule for target.
console_bridge: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 console_bridge
.PHONY : console_bridge

# fast build rule for target.
console_bridge/fast:
	$(MAKE) $(MAKESILENT) -f _deps/console_bridge-build/CMakeFiles/console_bridge.dir/build.make _deps/console_bridge-build/CMakeFiles/console_bridge.dir/build
.PHONY : console_bridge/fast

src/canbcm.o: src/canbcm.cpp.o
.PHONY : src/canbcm.o

# target to build an object file
src/canbcm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/socketcan_bcm.dir/build.make CMakeFiles/socketcan_bcm.dir/src/canbcm.cpp.o
.PHONY : src/canbcm.cpp.o

src/canbcm.i: src/canbcm.cpp.i
.PHONY : src/canbcm.i

# target to preprocess a source file
src/canbcm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/socketcan_bcm.dir/build.make CMakeFiles/socketcan_bcm.dir/src/canbcm.cpp.i
.PHONY : src/canbcm.cpp.i

src/canbcm.s: src/canbcm.cpp.s
.PHONY : src/canbcm.s

# target to generate assembly for a file
src/canbcm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/socketcan_bcm.dir/build.make CMakeFiles/socketcan_bcm.dir/src/canbcm.cpp.s
.PHONY : src/canbcm.cpp.s

src/candump.o: src/candump.cpp.o
.PHONY : src/candump.o

# target to build an object file
src/candump.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/socketcan_dump.dir/build.make CMakeFiles/socketcan_dump.dir/src/candump.cpp.o
.PHONY : src/candump.cpp.o

src/candump.i: src/candump.cpp.i
.PHONY : src/candump.i

# target to preprocess a source file
src/candump.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/socketcan_dump.dir/build.make CMakeFiles/socketcan_dump.dir/src/candump.cpp.i
.PHONY : src/candump.cpp.i

src/candump.s: src/candump.cpp.s
.PHONY : src/candump.s

# target to generate assembly for a file
src/candump.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/socketcan_dump.dir/build.make CMakeFiles/socketcan_dump.dir/src/candump.cpp.s
.PHONY : src/candump.cpp.s

src/socketcan_interface_plugin.o: src/socketcan_interface_plugin.cpp.o
.PHONY : src/socketcan_interface_plugin.o

# target to build an object file
src/socketcan_interface_plugin.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/socketcan_interface_plugin.dir/build.make CMakeFiles/socketcan_interface_plugin.dir/src/socketcan_interface_plugin.cpp.o
.PHONY : src/socketcan_interface_plugin.cpp.o

src/socketcan_interface_plugin.i: src/socketcan_interface_plugin.cpp.i
.PHONY : src/socketcan_interface_plugin.i

# target to preprocess a source file
src/socketcan_interface_plugin.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/socketcan_interface_plugin.dir/build.make CMakeFiles/socketcan_interface_plugin.dir/src/socketcan_interface_plugin.cpp.i
.PHONY : src/socketcan_interface_plugin.cpp.i

src/socketcan_interface_plugin.s: src/socketcan_interface_plugin.cpp.s
.PHONY : src/socketcan_interface_plugin.s

# target to generate assembly for a file
src/socketcan_interface_plugin.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/socketcan_interface_plugin.dir/build.make CMakeFiles/socketcan_interface_plugin.dir/src/socketcan_interface_plugin.cpp.s
.PHONY : src/socketcan_interface_plugin.cpp.s

src/string.o: src/string.cpp.o
.PHONY : src/string.o

# target to build an object file
src/string.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/socketcan_interface_string.dir/build.make CMakeFiles/socketcan_interface_string.dir/src/string.cpp.o
.PHONY : src/string.cpp.o

src/string.i: src/string.cpp.i
.PHONY : src/string.i

# target to preprocess a source file
src/string.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/socketcan_interface_string.dir/build.make CMakeFiles/socketcan_interface_string.dir/src/string.cpp.i
.PHONY : src/string.cpp.i

src/string.s: src/string.cpp.s
.PHONY : src/string.s

# target to generate assembly for a file
src/string.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/socketcan_interface_string.dir/build.make CMakeFiles/socketcan_interface_string.dir/src/string.cpp.s
.PHONY : src/string.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... console_bridge"
	@echo "... socketcan_bcm"
	@echo "... socketcan_dump"
	@echo "... socketcan_interface_plugin"
	@echo "... socketcan_interface_string"
	@echo "... src/canbcm.o"
	@echo "... src/canbcm.i"
	@echo "... src/canbcm.s"
	@echo "... src/candump.o"
	@echo "... src/candump.i"
	@echo "... src/candump.s"
	@echo "... src/socketcan_interface_plugin.o"
	@echo "... src/socketcan_interface_plugin.i"
	@echo "... src/socketcan_interface_plugin.s"
	@echo "... src/string.o"
	@echo "... src/string.i"
	@echo "... src/string.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

